# Generated by Django 5.1.3 on 2024-11-24 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_phone_divisionaloffice_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="divisionaloffice",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="divisional_office",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subdivisionaloffice",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_divisional_office",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
