# Generated by Django 5.1.3 on 2024-11-24 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("post_office", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("attachment", models.FileField(upload_to="attachments/")),
                ("date_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="CleaningStaff",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("contactNo", models.CharField(max_length=15)),
                (
                    "pincode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post_office.postoffice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventReport",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("report_description", models.TextField()),
                ("name", models.CharField(max_length=255)),
                ("atLocation", models.BooleanField(default=False)),
                ("attached_report", models.FileField(upload_to="reports/")),
                ("date_time", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="waste_management.event",
                    ),
                ),
                (
                    "pincode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post_office.postoffice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ewaste",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("no_of_units", models.PositiveIntegerField()),
                ("date_time", models.DateTimeField()),
                ("name", models.CharField(max_length=255)),
                (
                    "pincode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post_office.postoffice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperWaste",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("weight", models.FloatField()),
                ("date", models.DateField()),
                (
                    "pincode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post_office.postoffice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SelledPaperWaste",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("total_weight", models.FloatField()),
                ("selling_price_per_unit", models.FloatField()),
                ("total_price", models.FloatField()),
                (
                    "pincode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post_office.postoffice",
                    ),
                ),
            ],
        ),
    ]
