# Generated by Django 5.1.3 on 2024-11-24 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="selledpaperwaste",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="paperwaste",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
