# Generated by Django 5.1.3 on 2024-11-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subdivisionaloffice",
            name="division_pincode",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
