# Generated by Django 5.1.3 on 2024-11-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_subdivisionaloffice_division_pincode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="divisionaloffice",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="subdivisionaloffice",
            old_name="phone",
            new_name="phone_number",
        ),
    ]
